### ISSUE TITLE
密盒星球无法使用了，希望更新下

### ISSUE THREAD

**Issue by suzhenpeng** [Huansheng1/my-qinglong-js#13]

**Comment by suzhenpeng** [comment]
## 开始执行... 2023-10-31 11:18:45

密盒星球 开始运行：

共找到1个账号

================ 开始执行 ================
作者：幻生（禁止倒卖）
注册地址（非常感谢）：https://download.chiguavod.com/#/?inviteCode=95JGw7
脚本仓库（认准更新地址）：https://github.com/Huansheng1/my-qinglong-js
----------- 执行 第 [1] 个账号 -----------
账号[1] 登录成功
账号[1] 支持作者成功，感谢支持！

================ 任务队列构建完毕 ================
----------- 账号[1] -----------
账号[1] 查询用户信息成功，已绑定提现的微信账号名是 undefined
账号[1] 获取最新热门视频成功
账号[1] 查询账户概要成功，当前账户金币数：13628.0个，已领取今日视频红包，未提现1元额度现金，已提现0.3元额度现金
账号[1] 提现1元失败：提现人数过多，请选择其他提现选项
账号【1】第【1】次播放视频中，请等待18.70444153169234秒……
TypeError: Cannot read properties of null (reading '3')
    at /ql/scripts/Huansheng1_my-qinglong-js_main/密盒星球.js:46:47609
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async _0x14273d.adWhich (/ql/scripts/Huansheng1_my-qinglong-js_main/密盒星球.js:46:46203)
    at async _0x14273d.doTask (/ql/scripts/Huansheng1_my-qinglong-js_main/密盒星球.js:46:70195)
    at async /ql/scripts/Huansheng1_my-qinglong-js_main/密盒星球.js:46:73598
账号[1] 第0次领取视频奖励失败：运行时异常:
账号【1】第【2】次播放视频中，请等待24.85846554568486秒……
TypeError: Cannot read properties of null (reading '3')
    at /ql/scripts/Huansheng1_my-qinglong-js_main/密盒星球.js:46:47609
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async _0x14273d.adWhich (/ql/scripts/Huansheng1_my-qinglong-js_main/密盒星球.js:46:46203)
    at async _0x14273d.doTask (/ql/scripts/Huansheng1_my-qinglong-js_main/密盒星球.js:46:70195)
    at async /ql/scripts/Huansheng1_my-qinglong-js_main/密盒星球.js:46:73598
账号[1] 第0次领取视频奖励失败：运行时异常:
账号【1】第【3】次播放视频中，请等待18.76375136344096秒……
TypeError: Cannot read properties of null (reading '3')
    at /ql/scripts/Huansheng1_my-qinglong-js_main/密盒星球.js:46:47609
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async _0x14273d.adWhich (/ql/scripts/Huansheng1_my-qinglong-js_main/密盒星球.js:46:46203)
    at async _0x14273d.doTask (/ql/scripts/Huansheng1_my-qinglong-js_main/密盒星球.js:46:70195)
    at async /ql/scripts/Huansheng1_my-qinglong-js_main/密盒星球.js:46:73598
账号[1]调用post[watch_video]出错，返回状态码[404] 返回结果： <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /applet/mf/advertising/integral/watch/video was not found on this server.</p>
<hr>
<address>Apache/2.4.7 (Ubuntu) Server at :: Port 443</address>
</body></html>

账号[1] 第0次领取视频奖励失败：null
账号[1] 查询账户概要成功，当前账户金币数：13628.0个，已领取今日视频红包，未提现1元额度现金，已提现0.3元额度现金
账号[1] 提现1元失败：提现人数过多，请选择其他提现选项

密盒星球 运行结束，共运行了 106.136 秒！

## 执行结束... 2023-10-31 11:20:31 耗时 106 秒

**Comment by suzhenpeng** [comment]
更新后，仍然报错
## 开始执行... 2023-10-31 11:37:49

密盒星球 开始运行：

共找到1个账号

================ 开始执行 ================
作者：幻生（禁止倒卖）
注册地址（非常感谢）：https://download.chiguavod.com/#/?inviteCode=95JGw7
脚本仓库（认准更新地址）：https://github.com/Huansheng1/my-qinglong-js
----------- 执行 第 [1] 个账号 -----------
账号[1] 登录成功
账号[1] 支持作者成功，感谢支持！

================ 任务队列构建完毕 ================
----------- 账号[1] -----------
账号[1] 查询用户信息成功，已绑定提现的微信账号名是 undefined
账号[1] 获取最新热门视频成功
账号[1] 查询账户概要成功，当前账户金币数：13628.0个，已领取今日视频红包，未提现1元额度现金，已提现0.3元额度现金
账号[1] 提现1元失败：提现人数过多，请选择其他提现选项
账号【1】第【1】次播放视频中，请等待20.816213332642487秒……
TypeError: Cannot read properties of null (reading '3')
    at /ql/scripts/Huansheng1_my-qinglong-js_main/密盒星球.js:46:47609
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async _0x14273d.adWhich (/ql/scripts/Huansheng1_my-qinglong-js_main/密盒星球.js:46:46203)
    at async _0x14273d.doTask (/ql/scripts/Huansheng1_my-qinglong-js_main/密盒星球.js:46:70195)
    at async /ql/scripts/Huansheng1_my-qinglong-js_main/密盒星球.js:46:73598
账号[1] 第0次领取视频奖励失败：运行时异常:
账号【1】第【2】次播放视频中，请等待22.955635521161557秒……
TypeError: Cannot read properties of null (reading '3')
    at /ql/scripts/Huansheng1_my-qinglong-js_main/密盒星球.js:46:47609
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async _0x14273d.adWhich (/ql/scripts/Huansheng1_my-qinglong-js_main/密盒星球.js:46:46203)
    at async _0x14273d.doTask (/ql/scripts/Huansheng1_my-qinglong-js_main/密盒星球.js:46:70195)
    at async /ql/scripts/Huansheng1_my-qinglong-js_main/密盒星球.js:46:73598
账号[1] 第0次领取视频奖励失败：运行时异常:
账号【1】第【3】次播放视频中，请等待12.186227893414168秒……

**Comment by Huansheng1** [comment]
![image](https://github.com/Huansheng1/my-qinglong-js/assets/33859558/77e74c25-3546-4082-aabd-a9dbf38e82bd)
你确定你更新了？自己在青龙找到脚本和仓库的版本号对比下

**Comment by suzhenpeng** [comment]
重启了一下青龙可以了，大佬神速
